### PR TITLE
Fix failing tests in host apps

### LINKED ISSUE #116: Unable to run application tests when HONEYBADGER_API_KEY is not set
We just updated from 0.6.3 to 0.7.0, and discovered that we are no longer able to run our test suite without setting `HONEYBADGER_API_KEY` in the environment. This doesn't really make sense, because the test environment is listed in `:excluded_envs` in the honeybadger config.

Our quick workaround is to add an empty `HONEYBADGER_API_KEY` to our env, but it would be better if we only had to export the variable for environments where honeybadger was actually enabled.

```
** (Mix) Could not start application honeybadger: exited in: Honeybadger.start(:normal, [])
    ** (EXIT) an exception was raised:
        ** (ArgumentError) system variable "HONEYBADGER_API_KEY" is not set
            (honeybadger) lib/honeybadger.ex:233: Honeybadger.get_env/1
            (honeybadger) lib/honeybadger.ex:255: anonymous fn/2 in Honeybadger.get_all_env/0
            (elixir) lib/enum.ex:1811: Enum."-reduce/3-lists^foldl/2-0-"/3
            (honeybadger) lib/honeybadger.ex:254: Honeybadger.get_all_env/0
            (honeybadger) lib/honeybadger.ex:146: Honeybadger.start/2
            (kernel) application_master.erl:273: :application_master.start_it_old/4
```

### PR DESCRIPTION
**Pull request by minhajuddin**
Fixes #116

### CODE REVIEW

**Comment by joshuap** [comment]
@minhajuddin this also changes the behavior in non-dev environments; for example, the app will now boot with no API key in production. I'm not totally *against* allowing that, but I want to make sure we're explicitly making that decision before merging this. A few questions:

1. Do we want to take a softer approach to missing configuration options? The benefit of raising when config is missing is that it alerts the user immediately that errors won't be reported. The drawback is that it could crash their app if they forget to add the API key. I'm not sure which is most preferred in Elixir.
2. What happens when an API key isn't configure in a non-dev environment? Are error reports sent without an API key? In our Ruby gem we just log that the gem isn't configured instead of reporting the error.

/cc @sorentwo -- any thoughts on this?

**Comment by minhajuddin** [comment]
> What happens when an API key isn't configure in a non-dev environment? Are error reports sent without an API key? In our Ruby gem we just log that the gem isn't configured instead of reporting the error.

In an excluded_env, we create our payload but skip sending it to honeybadger. This is not the optimal thing.

We have three surface points that need to change based on our env.

 1. Starting a GenServer for the client: We should ideally not start a GenServer when we are in an excluded_env. However, we do a bit of initialization of our configuration in the GenServer. This should probably be moved to some other place.
 2. `Honeybadger.notify`: This builds up a context even in excluded envs and fails if honeybadger configuration hasn't been fully setup. Ideally, we should replace this function with a noop when in an excluded env
 3. `Honeybadger.Plug`: This too builds up a lot of context and calls the notify. Ideally this plug should be a noop too in an excluded env.

I took a stab at these but ran into a few issues with configuration not being available at compile time. Let me take another stab at this tomorrow. Ideally we should let honeybadger crash the app for lack of an api_key as that will make people either add the env to `exclude_env` or set up an `api_key`

**Comment by sorentwo** [comment]
I err on the side of logging for missing values rather than enforcing them with a runtime error. With the new mix task to verify setup users can be confident that they got things working.

Elixir already has facilities to make sure applications aren't started unnecessarily, either by specifying them as only loading in certain environments or excluding them from the applications list in older versions.

In any case, sprinkling multiple modules with extra conditionals seems heavy handed and prone to breakage.

**Comment by minhajuddin** [comment]
@joshuap I think with the way the app is structured, this is the minimal patch that will fix the error and also show a warning if honeybadger is started in a non excluded env without an api_key. Please review this PR and let me know if you'd like to change anything.

**Comment by joshuap** [comment]
I think this needs a bit more work/thought. There are really two cases here:

1. When in an excluded environment. In this case we don't care about valid configuration; we just want to warn the user that reporting live data to Honeybadger is disabled. In our ruby gem we log this message:

> Development mode is enabled. Data will not be reported until you deploy your app.

I'm OK with still going through some steps to build the payload, etc. in an excluded environment as long as the notice is not actually sent. Stubbing out the server logic late in the process has the benefit of covering more honeybadger code in the user's tests.

2. When in a live environment, we want to warn the user when an API key isn't present. Honestly, the API key is the only thing that we really need -- our API/UI can handle null environments. So maybe we should just log a warning if the API key isn't configured.

We also should make sure that if an error is reported *and there is no valid API key*, we don't attempt to send the notice.

@minhajuddin what do you think?

**Comment by minhajuddin** [comment]
> When in an excluded environment. In this case we don't care about valid configuration...
We now show a warning in this scenario.

> We also should make sure that if an error is reported and there is no valid API key, we don't attempt to send the notice.
We now don't send notices when there is no valid api key

File: lib/honeybadger/client.ex [hunk 1]
```diff
@@ -71,11 +72,32 @@ defmodule Honeybadger.Client do
   # Callbacks
 
   def init(state) do
+    warn_if_incomplete_env(state)
```
Comment (joshuap) [inline lib/honeybadger/client.ex]: What currently happens if an API key is configured but the environment name isn't? I'm wondering if we still need to make `environment_name` mandatory or if this could just warn if the API key is missing.

File: lib/honeybadger/client.ex [hunk 2]
```diff
@@ -71,11 +72,32 @@ defmodule Honeybadger.Client do
...
 
     {:ok, state}
   end
 
+  @mandatory_keys ~w[api_key environment_name]a
+  defp warn_if_incomplete_env(%{enabled: true}) do
+    @mandatory_keys
+    |> Enum.each(fn key ->
+      if !Honeybadger.get_env(key) do
+        Logger.error("mandatory :honeybadger config key #{key} not set")
```
Comment (joshuap) [inline lib/honeybadger/client.ex]: I think this should be `Logger.warn`, like the dev mode warning. This isn't really an error.

File: lib/honeybadger/client.ex (hunk 1 above)
Comment (minhajuddin) [reply lib/honeybadger/client.ex]: > What currently happens if an API key is configured but the environment name isn't?

It prints out an error `mandatory :honeybadger config key :environment_name not set`. The default value of `:environment_name` is set to `Mix.env()`, so it wouldn't be nil unless it is set to nil (https://github.com/honeybadger-io/honeybadger-elixir/blob/master/mix.exs#L30).

However, it doesn't stop sending notices. It stops sending notices only if the `api_key` is missing.

File: lib/honeybadger/client.ex (hunk 2 above)
Comment (minhajuddin) [reply lib/honeybadger/client.ex]: This runs only in a non excluded env. Shouldn't we print an error if `api_key` is missing? This however checks for both `api_key` and `environment_name`

Comment (joshuap) [reply lib/honeybadger/client.ex]: Ah yeah, that sounds right.

File: lib/honeybadger/client.ex (hunk 1 above)
Comment (joshuap) [reply lib/honeybadger/client.ex]: Makes sense. Let's just roll with this.
