### PR TITLE
Encode notice message iodata before json serialize

### LINKED ISSUE #356: "FunctionClauseError: no function clause matching in Jason.Encode.list_loop/3" from HB reporting
I saw this error logged here: https://app.honeybadger.io/projects/72231/faults/78372903

The backtrace makes me think our app had a DB connection error but Honeybadger's reporting encountered an error trying to show that error, and reported its own error instead.

Message:

```
no function clause matching in Jason.Encode.list_loop/3

The following arguments were given to Jason.Encode.list_loop/3:

    # 1
    "** (DBConnection.ConnectionError) ssl recv: timeout"

    # 2
    #Function<3.48815102/3 in Jason.Encode."-fun.escape_json/3-">

    # 3
    #Function<1.48815102/3 in Jason.Encode."-fun.map_naive/3-">

Attempted function clauses (showing 2 out of 2):

    defp list_loop(-[]-, _escape, _encode_map)
    defp list_loop(-[head | tail]-, escape, encode_map)
```

Backtrace:

```
no function clause matching in Jason.Encode.list_loop/3 The following arguments were given to Jason.Encode.list_loop/3: # 1 "** (DBConnection.ConnectionError) ssl recv: timeout" # 2 #Function<3.48815102/3 in Jason.Encode."-fun.escape_json/3-"> # 3 #Function<1.48815102/3 in Jason.Encode."-fun.map_naive/3-"> Attempted function clauses (showing 2 out of 2): defp list_loop(-[]-, _escape, _encode_map) defp list_loop(-[head | tail]-, escape, encode_map)
lib/encode.ex:147:in `list_loop/3'
lib/encode.ex:153:in `list_loop/3'
lib/encode.ex:144:in `list/3'
lib/encode.ex:182:in `map_naive_loop/3'
lib/encode.ex:183:in `map_naive_loop/3'
lib/encode.ex:173:in `map_naive/3'
lib/honeybadger/notice.ex:40:in `encode/2'
lib/encode.ex:35:in `encode/2'
````

### PR DESCRIPTION
**Pull request by sorentwo**
Notice messages are sometimes provided as iodata, which may be an improper list where the last cons is to a binary rather than a list. That format isn't encodeable by Jason and causes a function clause error in `Jason.Encode.list_loop/3`. This caused a secondary error to fire for every error with an improper list.

This fixes the situation by converting iodata to binary before encoding and sending the notice.

Closes #356

### CODE REVIEW

**Comment by sorentwo** [comment]
@bayprogrammer @henrik 👀

**Comment by sorentwo** [comment]
@joshuap We should release a new patch version after this is merged.

File: test/honeybadger_test.exs [hunk 1]
```diff
@@ -159,6 +159,17 @@ defmodule HoneybadgerTest do
...
+
+    test "sending a notice when the message is an improper list of iodata" do
+      restart_with_config(exclude_envs: [])
+
+      message = ["RealError", 32, 40, "#PID<0.1.0>" | " ** Error"]
+
+      Honeybadger.notify(%RuntimeError{message: message})
+
+      assert_receive {:api_request, %{"error" => error}}
+      assert error["message"] == "RealError (#PID<0.1.0> ** Error"
```
Comment (henrik) [inline test/honeybadger_test.exs:171]: Out of curiosity, why the unbalanced parentheses here? CI seems to pass so I assume it’s not a typo.

Comment (sorentwo) [reply test/honeybadger_test.exs:171]: The open parens came from two integers in the iodata. The last value in the improper list is a binary with a made up error. Together they show that iodata is getting converted correctly, even though the message is totally fake.

Comment (henrik) [reply test/honeybadger_test.exs:171]: Ah, doh. Cheers :)

**Review by joshuap — APPROVED** [review]
LGTM. I'll merge and release a patch.

**Comment by joshuap** [comment]
0.16.2 has been released :shipit:
